production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_account_sid:  <%= ENV.fetch("TWILIO_ACCOUNT_SID", "AC5658f5b3db1822c4316e867581b01604") %>
  twilio_auth_token:  <%= ENV.fetch("TWILIO_AUTH_TOKEN", "0b650725d214c83b69d1fd7750e9cd88") %>
  twilio_phone_number:  <%= ENV.fetch("TWILIO_PHONE_NUMBER", "+17864085118") %>

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_account_sid:  <%= ENV.fetch("TWILIO_ACCOUNT_SID", "AC5658f5b3db1822c4316e867581b01604") %>
  twilio_auth_token:  <%= ENV.fetch("TWILIO_AUTH_TOKEN", "0b650725d214c83b69d1fd7750e9cd88") %>
  twilio_phone_number:  <%= ENV.fetch("TWILIO_PHONE_NUMBER", "+17864085118") %>
